#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.html
sudo service nginx start
