#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
sudo chown $USER:$USER
/var/www/html/index.html
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
